### ISSUE TITLE
Code Louisville Courses to be Completed

### ISSUE THREAD

**Issue by jmpeck** [jmpeck/Code-Louisville-Project#2]
##TODO
*Courses left to complete the Code Louisville Treehouse Track*

* [ ] HTML Video and Audio
* [ ] Responsive Layouts
* [ ] AJAX Basics
* [ ] Object-Oriented JavaScript
* [ ] Accessibility
* [ ] Website Optimization
* [ ] Front End Performance Optimization
* [ ] Introduction to Design Patterns
* [ ] Framework Basics
